kind: pipeline
type: dokcer
name: default

steps:
  - name: go build
    image: javier1/go-goreleaser:latest
    commands:
      - bash
      - /scrypt/aws-cleaner.sh

trigger:
  branch:
    - master
  event:
    - push
